services:
  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports: [3306:3306]
    volumes:
      - db-data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports: [1025:1025, 8025:8025]

  redis:
    image: redis
    ports: [6379:6379]

  nginx:
    image: nginx
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./nginx/server.crt:/etc/nginx/server.crt
      # - ./nginx/server.key:/etc/nginx/server.key
      - ~/Code:/home/matthieu/Code

  php84: &php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.4
    ports:
      - 9084:9000
      - 8084:8000
    user: matthieu
    volumes:
      - ~/Code:/home/matthieu/Code

  php83:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.3
    ports:
      - 9083:9000
      - 8083:8000

  php82:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.2
    ports:
      - 9082:9000
      - 8082:8000

  php81:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.1
    ports:
      - 9081:9000
      - 8081:8000

  php80:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: '8.0'
    ports:
      - 9080:9000
      - 8080:8000

  php74:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 7.4
    ports:
      - 9074:9000
      - 8074:8000

volumes:
  db-data:
