services:
  database:
    image: alpine/socat:latest
    network_mode: host
    command: TCP-LISTEN:3306,fork,bind=host.docker.internal TCP-CONNECT:127.0.0.1:3306
    extra_hosts:
      - host.docker.internal:host-gateway

  php82: &php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.2
    ports:
      - 9082:9000
      - 8082:8000
    user: matthieu
    volumes:
      - ~/Code:/home/matthieu/Code
    extra_hosts:
      - host.docker.internal:host-gateway

  php81:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 8.1
    ports:
      - 9081:9000
      - 8081:8000

  php74:
    <<: *php
    build:
      context: ./php
      args:
        PHP_VERSION: 7.4
    ports:
      - 9074:9000
      - 8074:8000
